using MySingingMonsterKaraokeStudio.Models;

namespace MySingingMonsterKaraokeStudio.Services;

public sealed class MidiService
{
    private const int TicksPerBeat = 480;
    public void Write(SongProject project, string path)
    {
        ChartValidation.Validate(project);
        using var track = new MemoryStream();
        var tempo = (int)Math.Round(60_000_000 / project.Bpm);
        track.Write([0, 0xff, 0x51, 3, (byte)(tempo >> 16), (byte)(tempo >> 8), (byte)tempo]);
        track.Write([0, 0xff, 0x58, 4, (byte)project.TimeSignature, 2, 24, 8]);
        var events = AudioDraftService.CropNotes(project.Notes, project.OffsetSeconds, 0, double.MaxValue).SelectMany(n => new[]
        {
            (Tick: Tick(n.Time, project.Bpm), On: true, Pitch: n.Pitch),
            (Tick: Math.Max(Tick(n.Time, project.Bpm) + 1, Tick(n.Time + n.Length, project.Bpm)), On: false, Pitch: n.Pitch)
        }).OrderBy(e => e.Tick).ThenBy(e => e.On).ToList();
        var previous = 0;
        foreach (var e in events)
        {
            WriteVariable(track, e.Tick - previous); previous = e.Tick;
            track.WriteByte(e.On ? (byte)0x90 : (byte)0x80); track.WriteByte((byte)Math.Round(e.Pitch)); track.WriteByte(e.On ? (byte)100 : (byte)0);
        }
        track.Write([0, 0xff, 0x2f, 0]);
        var temporary = path + "." + Guid.NewGuid().ToString("N") + ".tmp";
        try
        {
            using (var output = File.Create(temporary))
            {
                output.Write("MThd"u8); WriteBigEndian(output, 6, 4); WriteBigEndian(output, 0, 2); WriteBigEndian(output, 1, 2); WriteBigEndian(output, TicksPerBeat, 2);
                output.Write("MTrk"u8); WriteBigEndian(output, checked((int)track.Length), 4); track.Position = 0; track.CopyTo(output);
            }
            File.Move(temporary, path, true);
        }
        finally { if (File.Exists(temporary)) File.Delete(temporary); }
    }

    public List<ChartNote> Read(string path)
    {
        using var input = new BinaryReader(File.OpenRead(path));
        if (!input.ReadBytes(4).SequenceEqual("MThd"u8.ToArray()) || ReadBigEndian(input, 4) != 6)
            throw new InvalidDataException("Invalid MIDI header.");
        if (ReadBigEndian(input, 2) != 0 || ReadBigEndian(input, 2) != 1)
            throw new InvalidDataException("Open a single-track MIDI generated by this studio.");
        var division = ReadBigEndian(input, 2);
        if (division <= 0 || division >= 0x8000 || !input.ReadBytes(4).SequenceEqual("MTrk"u8.ToArray())) throw new InvalidDataException("Unsupported MIDI timing.");
        var length = ReadBigEndian(input, 4);
        if (length < 0 || length > input.BaseStream.Length - input.BaseStream.Position) throw new InvalidDataException("Invalid MIDI track length.");
        using var reader = new BinaryReader(new MemoryStream(input.ReadBytes(length)));
        var active = new Dictionary<(int Channel, int Pitch), Queue<double>>();
        var notes = new List<ChartNote>();
        double time = 0, tempo = 500000;
        byte running = 0;
        while (reader.BaseStream.Position < reader.BaseStream.Length)
        {
            time += ReadVariable(reader) * tempo / division / 1_000_000;
            var status = reader.ReadByte();
            if (status < 0x80)
            {
                if (running == 0) throw new InvalidDataException("Invalid MIDI running status.");
                reader.BaseStream.Position--; status = running;
            }
            if (status == 0xff)
            {
                var type = reader.ReadByte(); var count = ReadVariable(reader); var data = reader.ReadBytes(count);
                if (data.Length != count) throw new InvalidDataException("Truncated MIDI metadata.");
                if (type == 0x51 && count == 3) tempo = data[0] * 65536 + data[1] * 256 + data[2];
                if (type == 0x2f) break;
                continue;
            }
            if (status is 0xf0 or 0xf7) { reader.ReadBytes(ReadVariable(reader)); running = 0; continue; }
            if (status >= 0xf0) throw new InvalidDataException("Unsupported MIDI event.");
            running = status;
            var pitch = reader.ReadByte();
            if ((status & 0xf0) is 0xc0 or 0xd0) continue;
            var velocity = reader.ReadByte(); var key = (status & 0xf, (int)pitch);
            if ((status & 0xf0) == 0x90 && velocity > 0)
            {
                if (!active.TryGetValue(key, out var starts)) active[key] = starts = new();
                starts.Enqueue(time);
            }
            else if (((status & 0xf0) == 0x80 || ((status & 0xf0) == 0x90 && velocity == 0)) && active.TryGetValue(key, out var starts) && starts.Count > 0)
            {
                var start = starts.Dequeue();
                if (time > start) notes.Add(new ChartNote { Time = start, Length = time - start, Pitch = pitch, EndPitch = pitch });
            }
        }
        return notes.OrderBy(n => n.Time).ToList();
    }

    private static int Tick(double seconds, double bpm)
    {
        var tick = Math.Round(seconds * bpm / 60 * TicksPerBeat);
        if (!double.IsFinite(tick) || tick < 0 || tick > int.MaxValue - 1) throw new InvalidDataException("A note exceeds MIDI's supported duration.");
        return (int)tick;
    }
    private static void WriteBigEndian(Stream stream, int value, int bytes) { for (var i = bytes - 1; i >= 0; i--) stream.WriteByte((byte)(value >> (i * 8))); }
    private static int ReadBigEndian(BinaryReader reader, int bytes) { var value = 0; for (var i = 0; i < bytes; i++) value = (value << 8) | reader.ReadByte(); return value; }
    private static void WriteVariable(Stream stream, int value)
    {
        if (value is < 0 or > 0x0fffffff) throw new InvalidDataException("A MIDI event gap is too long.");
        Span<byte> bytes = stackalloc byte[4]; var i = 3; bytes[i] = (byte)(value & 127);
        while ((value >>= 7) > 0) bytes[--i] = (byte)((value & 127) | 128);
        stream.Write(bytes[i..]);
    }
    private static int ReadVariable(BinaryReader reader)
    {
        var value = 0;
        for (var i = 0; i < 4; i++) { var b = reader.ReadByte(); value = (value << 7) | (b & 127); if ((b & 128) == 0) return value; }
        throw new InvalidDataException("Invalid MIDI event duration.");
    }
}
